#! /usr/bin/env bash
set -u
set -e

if [ -z "${1+foo}" ]; then
	echo "Usage: add-script <name>"
	exit
fi

dir=~/.toolchain
touch $dir/$1
echo '#! /usr/bin/env bash' > $dir/$1
chmod +x $dir/$1
$EDITOR $dir/$1
