#! /usr/bin/env bash
if [[ -z "$1" ]]; then
  echo Available s3 buckets are:
  aws s3 ls | awk '{print $3}'
else
  aws s3 ls s3://$1 --recursive \
  | grep -v -E "(Bucket: |Prefix: |LastWriteTime|^$|--)" \
  | awk 'BEGIN {total=0}{total+=$3}END{print total/1024/1024/1024"GB $"total/1024/1024/1024*.03"/month"}'
fi
