#!/usr/bin/fish
set -l prompt_mode
for arg in $argv
  switch "$arg"
  case --prompt
    set prompt_mode 1
  end
end

set -l percent (cat /sys/class/power_supply/BAT0/capacity)
set -l power_letter
if grep -q 1 /sys/class/power_supply/ADP1/online
  set power_letter =
else
  set power_letter 0
end

if [ -n "$prompt_mode" ]
  echo "$power_letter $percent%"
else
  echo $percent
end
