#! /usr/bin/env bash

active_host=$(docker-machine active 2> /dev/null || echo none)

if [[ $active_host != none ]]; then
	echo "You are currently attached to docker machine node: $active_host"
	exit
fi

docker ps -qa | xargs docker rm -v $@
