#! /usr/bin/env bash
set -u
set -e

if [ -z "${1+foo}" ]; then
	echo "Usage: make-tool <name>"
	exit
fi

script_type=${2:-bash}
dir=~/.toolchain

[ -f $dir/$1 ] || {
	touch $dir/$1
	echo "#! /usr/bin/env $script_type" > $dir/$1
	chmod +x $dir/$1
}

$EDITOR $dir/$1
